spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER_NAME:discodeit_user}
    password: ${DB_USER_PASSWORD:discodeit1234}

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081

logging:
  level:
    root: debug
    com.sprint.mission: debug
