spring:
  application:
    name: discodeit

  boot:
    admin:
      client:
        enabled: false

  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB # 한 번에 최대 업로드 가능 용량

  datasource:
  # 환경별로 오버라이드
  # url: jdbc:postgresql://localhost:5432/discodeit
  # username: ${USER_NAME}
  # password: ${USER_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: true
        default_batch_fetch_size: 100
        format_sql: false
        show_sql: false

discodeit:
  storage:
    type: "local"
    local:
      root-path: .discodeit/binary-content

decorator:
  datasource:
    p6spy:
      enable-logging: true

logging:
  level:
    root: info
    com.sprint.mission: info

# 기본값 외 실제 또는 추가 설정은 프로필 설정에서 오버라이드.