spring:
  datasource:
    url:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER_NAME}
    password: ${DB_USER_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8080

logging:
  level:
    root: info
    com.sprint.mission: info

decorator:
  datasource:
    p6spy:
      enable-logging: false
