spring:
  config:
    activate:
      on-profile: test
  application:
    name: discodeit
  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        default_batch_fetch_size: 100
        format_sql: true
    open-in-view: false

discodeit:
  repository:
    type: file
    file-directory:
      folder: .discodeit-test
      user: "/user"
      user-status: "/user-status"
      channel: "/channel"
      message: "/message"
      binary-content: "/binary-content"
      read-status: "/read-status"
